nmea_parse.rpi:
	#arm-linux-gnueabihf-g++ -o nmea_parse.rpi -fPIC --std=c++17 -I/usr/arm-linux-gnueabihf/include/ nmea_parse.cpp
	#arm-linux-gnueabihf-g++ -o nmea_parse_O3.rpi -O3 -fPIC -std=c++17 -I/usr/arm-linux-gnueabihf/include/ nmea_parse.cpp
	arm-linux-gnueabihf-g++ -o nmea_parse_O2.rpi -O2 -fPIC -std=c++17 -I/usr/arm-linux-gnueabihf/include/ nmea_parse.cpp
	#arm-linux-gnueabihf-g++ -o nmea_parse_O1.rpi -O1 -fPIC -std=c++17 -I/usr/arm-linux-gnueabihf/include/ nmea_parse.cpp
	#arm-linux-gnueabihf-g++ -o nmea_parse_Os.rpi -Os -fPIC -std=c++17 -I/usr/arm-linux-gnueabihf/include/ nmea_parse.cpp
